models:
  - name: gold_revenue
    description: "Aggregated revenue"
    columns:
      - name: 'sale_date'
        description: "Date of sale"
        data_tests:
          - unique
          
           
  - name: silver_revenue
    description: "Cleansed revenue"
    columns:
      - name: sale_id
        description: "Primary Key"
        data_tests:
          - unique
          - not_null
      - name: total_revenue
        description: "Revenue generated"
        data_tests:
          - not_null
      - name: quantity_sold
        data_tests:
          - not_null
          
          
       

       
